baseURL = 'https://kazufumi1014.github.io/'
languageCode = 'en-us'
title = '꒰ ՞・ﻌ・՞ ꒱ cooking note 📖' 
theme = 'hugo-bearblog'
[params]
  favicon = "images/favicon_inu.ico"
  apple_touch_icon = "images/apple-touch-icon.png"
